### PR TITLE
Don't assume `document.documentElement` is non-null

### LINKED ISSUE #1756: Content script assumes `document.documentElement` is always non-null
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The uBlock Origin content script assumes `document.documentElement` and `document.body` are always non-null (see [js/contentscript.js#L396-L401](https://github.com/gorhill/uBlock/blob/f0b46bde4f8f9a05169dbb6ecdea0ba858cde165/src/js/contentscript.js#L396-L401)). This results in the following error being emitted in the browser console for any sites using Transcend Consent Manager:

Screen Shot 2021-10-11 at 5 58 37 PM

Transcend Consent Manager's sync endpoint iframe does not contain any `Element` nodes by the time uBlock Origin attempts to register a mutation observer on `document.documentElement`. The solution is to register the MutationObserver on `document`, not `document.documentElement`.

I also noticed a few other areas that assume common DOM interfaces are always non-null:
- [js/contentscript.js#L472](https://github.com/gorhill/uBlock/blob/f0b46bde4f8f9a05169dbb6ecdea0ba858cde165/src/js/contentscript.js#L472)
- [js/contentscript.js#L1174-L1177](https://github.com/gorhill/uBlock/blob/f0b46bde4f8f9a05169dbb6ecdea0ba858cde165/src/js/contentscript.js#L1174-L1177)
- [js/scriptlets/dom-inspector.js#L250](https://github.com/gorhill/uBlock/blob/7bf9a83d8e3fd59eb8359455554137aa6a1cc3be/src/js/scriptlets/dom-inspector.js#L250)

### A specific URL where the issue occurs

https://transcend.io/

### Steps to Reproduce

1. Navigate to https://transcend.io/ (or any other website using Transcend Consent Manager)

### Expected behavior

I don't expect to see any error.

### Actual behavior

I see an unsightly error in my console. This does not affect website functionality.

### uBlock Origin version

1.38.4

### Browser name and version

Google Chrome Version 94.0.4606.71

### Operating System and version

Mac OS 11.6

### PR DESCRIPTION
**Pull request by eligrey**
This PR fixes uBlockOrigin/uBlock-issues#1756

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

File: src/js/scriptlets/dom-inspector.js [hunk 1]
```diff
@@ -264,15 +264,17 @@ const domLayout = (function() {
                 continue;
             }
             // sibling
-            if ( node.nextElementSibling === null ) {
-                do {
-                    node = stack.pop();
+            if (node instanceof Element) {
```
Comment (eligrey) [inline src/js/scriptlets/dom-inspector.js:267]: @gorhill just realized that this should probably be `if (node.nodeType === 1)` for better perf and cross-realm element compatibility if those nodes could somehow get here

Comment (eligrey) [reply src/js/scriptlets/dom-inspector.js:267]: submitted a pr to fix this: https://github.com/gorhill/uBlock/pull/3942
